FROM nginx
COPY ./certs/my-example.localhost.crt /etc/nginx/my-example.localhost.crt
COPY ./certs/my-example.localhost.key /etc/nginx/my-example.localhost.key
COPY ./certs/my-example-api.localhost.crt /etc/nginx/my-example-api.localhost.crt
COPY ./certs/my-example-api.localhost.key /etc/nginx/my-example-api.localhost.key
COPY ./default.conf /etc/nginx/conf.d/default.conf
